version: '3'
services:
    mysql-server:
        image: mysql:5.7
        hostname: mysql-server
        container_name: mysql-server
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: userpass
        volumes:
        - ./db/dumps:/docker-entrypoint-initdb.d
        - ./db/data:/var/lib/mysql
        networks:
        - mysql-net

    node-app:
        image: abassi/nodejs-server:10.0-dev
        hostname: nodejs-container
        container_name: nodejs-container
        restart: always
        volumes:
        - .:/home/node/app
        networks:
        - mysql-net
        depends_on:
        - mysql-server
        ports:
        - "8000:3000"
        command: nodemon ws/index.js

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        hostname: phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql-server
        networks:
        - mysql-net
        depends_on:
        - mysql-server
        ports:
        - "8085:80"

networks:
    mysql-net:
        driver: bridge
